repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.57.2
    hooks:
      - id: golangci-lint
        args: ["--timeout=5m"]
        stages: [commit]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@3.1.0"]
        stages: [commit]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.1.0
    hooks:
      - id: eslint
        files: ^frontend/src/.*\.(ts|tsx|js|jsx)$
        stages: [commit]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: bash -c 'diff -u <(echo -n) <(gofmt -l .)' # show files needing fmt
        language: system
        pass_filenames: false
        stages: [commit]
      - id: go-mod-tidy
        name: go mod tidy check
        entry: bash -c 'cd backend && go mod tidy && git diff --exit-code'
        language: system
        pass_filenames: false
        stages: [commit]
